console.log("Print first program");
console.log("print second program");
console.log("print third program");
sumOfNumbers(5,10);
console.log("Print fourth program");
console.log("print fifth program");
console.log("print sixth program");
sumof(b+c);
console.log("Print seventh program");
console.log("print eight program");
console.log("print ninth program");